name: Run Jest tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  jestTest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
        env:
          URI: ${{ secrets.URI }}
          DATABASE: ${{ vars.DATABASE }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      - run: npm i
      - run: npm test
